In [2]:
import pandas as pd

In [3]:
house = pd.read_csv('29910226_solution.csv')
house.head()

,ID,Address,Suburb,Price,Type,Date,Rooms,Bathroom,Car,Landsize,Age,Lattitude,Longtitude,train_station_id,distance_to_train_station,travel_min_to_CBD,over_priced?,crime_A_average,crime_B_average,crime_C_average
0,ID524428873,14 Woodmason St,MALVERN,1437000.0,h,16/04/2016,3,1.0,1.0,313.0,109.0,-37.85110,145.03170,19945,1240.535013,19.214286,0,610,1743,228
1,ID455142191,85 Radford Rd,RESERVOIR,791000.0,h,18/06/2016,5,3.0,1.0,961.0,34.0,-37.70240,144.98400,19961,2223.991693,39.000000,0,824,1890,159
2,ID385314378,34 Fewster Dr,WANTIRNA SOUTH,970000.0,h,26/08/2017,3,2.0,2.0,674.0,38.0,-37.88360,145.22805,19869,5582.978901,48.181818,0,98,190,19
3,ID205782381,41 Adelaide St,ALBION,760000.0,h,23/09/2017,3,1.0,1.0,697.0,69.0,-37.78036,144.81950,20004,548.114894,26.375000,1,298,735,154
4,ID574190434,1/221 Westgarth St,NORTHCOTE,865000.0,t,12/11/2016,3,1.0,2.0,184.0,13.0,-37.78250,145.01040,19929,413.938549,19.923077,0,136,302,42

In [8]:
house[house['Address'].duplicated()]

,ID,Address,Suburb,Price,Type,Date,Rooms,Bathroom,Car,Landsize,Age,Lattitude,Longtitude,train_station_id,distance_to_train_station,travel_min_to_CBD,over_priced?,crime_A_average,crime_B_average,crime_C_average
58,ID227991548,33 Mountain St,SOUTH MELBOURNE,1150000.0,h,7/05/2016,2,1.0,0.0,113.0,163.0,-37.83730,144.94930,20043,2124.124142,0.000000,0,1100,3636,457
80,ID758306752,43 Ballantyne St,THORNBURY,925000.0,h,24/09/2016,2,1.0,1.0,258.0,49.0,-37.75840,144.99710,20014,393.597896,25.300000,0,2403,5212,586
202,ID946117206,10/3 Allard St,BRUNSWICK WEST,275000.0,u,15/07/2017,1,1.0,1.0,1388.0,49.0,-37.76840,144.94214,19968,1539.034668,25.333333,0,941,5813,575
218,ID386128852,114 Reynard St,COBURG,1064000.0,h,8/10/2016,3,2.0,1.0,417.0,79.0,-37.74780,144.95830,19965,750.738627,32.000000,0,1071,5783,419
261,ID155519306,2 Hazel St,CAMBERWELL,2125000.0,h,28/05/2016,5,3.0,2.0,603.0,39.0,-37.84370,145.06900,19850,578.227892,26.666667,0,3703,18944,2039
282,ID636472299,23/530 Toorak Rd,TOORAK,511000.0,u,27/06/2016,2,1.0,2.0,0.0,49.0,-37.84240,145.01840,19946,1010.013951,18.214286,0,584,2731,211
345,ID650392186,2/41 Kangaroo Rd,MURRUMBEENA,1220500.0,u,24/06/2017,3,2.0,2.0,462.0,54.0,-37.89767,145.07332,19918,489.753428,27.354839,0,298,735,154
429,ID469847752,8/37 Victoria St,ELSTERNWICK,740000.0,u,8/04/2017,2,1.0,1.0,0.0,59.0,-37.88810,145.00970,19954,858.805584,21.500000,0,1666,9333,523
523,ID589650660,11 Kerferd St,COBURG,941000.0,h,13/05/2017,2,1.0,2.0,413.0,29.0,-37.73550,144.95450,19964,767.256262,34.000000,1,1097,5916,553
543,ID880656809,56 Pecham St,GLENROY,621000.0,h,22/04/2017,3,1.0,1.0,694.0,49.0,-37.69770,144.91160,20031,471.000192,38.000000,0,1841,9184,533
547,ID138732004,14 Arthur St,CAULFIELD NORTH,1365000.0,h,3/09/2016,3,1.0,0.0,513.0,99.0,-37.86780,145.02700,19944,264.978755,20.800000,0,1540,6062,477
553,ID472390759,301/89 River St,SOUTH YARRA,930000.0,u,3/09/2016,2,2.0,2.0,0.0,19.0,-37.83610,144.99660,19959,456.584600,12.543860,0,1100,3636,457
563,ID236752982,76 Ogilvie St,ESSENDON,960000.0,h,4/03/2017,3,1.0,2.0,549.0,69.0,-37.74790,144.89310,22253,2225.748542,18.333333,0,330,1855,82
571,ID470285370,1/36 Pleasant Rd,HAWTHORN EAST,1738000.0,t,15/10/2016,4,3.0,2.0,324.0,17.0,-37.83480,145.05030,19853,1175.366689,19.090909,0,1144,6845,375
577,ID707383464,25 Hardy St,BRUNSWICK,1500000.0,h,3/12/2016,4,3.0,1.0,365.0,129.0,-37.76240,144.96710,19967,579.772363,27.333333,0,958,5673,628
585,ID337914978,1/36 The Avenue,BALACLAVA,585000.0,u,15/07/2017,2,1.0,1.0,598.0,44.0,-37.87149,144.99746,19956,412.373168,17.500000,0,1672,10063,646
592,ID968176576,59 Sellars St,WATSONIA NORTH,850000.0,h,22/07/2017,3,1.0,2.0,766.0,45.0,-37.69821,145.08995,19984,1515.494309,37.666667,0,281,524,75
608,ID282152385,73 Pecham St,GLENROY,963500.0,h,27/05/2017,3,2.0,6.0,697.0,59.0,-37.69647,144.91130,20031,427.970359,38.000000,0,1841,9184,533
633,ID589073637,141 Gold St,BRUNSWICK,845500.0,h,7/05/2016,2,1.0,1.0,179.0,129.0,-37.77420,144.95420,19969,407.417428,24.333333,0,958,5673,628
650,ID384557170,7 Fairbairn Rd,SUNSHINE WEST,520000.0,h,3/06/2017,3,2.0,2.0,535.0,39.0,-37.79414,144.81855,22241,1406.976619,15.850000,0,2532,5455,713
670,ID630270562,4 Tudor Rd,DONCASTER,1540500.0,h,9/09/2017,5,2.0,2.0,726.0,49.0,-37.78133,145.10833,19896,4235.621140,28.785714,0,1666,9333,523
671,ID389916108,44 Severn St,YARRAVILLE,1930000.0,h,10/12/2016,3,1.0,4.0,902.0,99.0,-37.81530,144.87960,19996,911.952040,11.357143,0,703,1502,135
674,ID521656880,239 Punt Rd,RICHMOND,1570000.0,h,27/06/2016,3,1.0,2.0,248.0,59.0,-37.81980,144.98990,22247,475.005247,10.000000,0,824,1890,159
698,ID637311098,3/302 Grange Rd,ORMOND,405000.0,u,28/08/2016,2,1.0,1.0,0.0,49.0,-37.90310,145.04440,19941,421.151969,32.153846,0,268,736,128
700,ID631497594,4 Ella Ct,DONCASTER,1300000.0,h,8/04/2017,4,2.0,2.0,872.0,49.0,-37.79060,145.11380,20042,3247.061519,25.775000,0,1666,9333,523
701,ID713631606,71 Hume Av,MELTON SOUTH,410000.0,h,9/09/2017,4,1.0,2.0,578.0,39.0,-37.71077,144.57198,19980,831.226898,39.600000,0,50,68,12
702,ID198657690,25 Faversham Rd,CANTERBURY,2510000.0,h,13/05/2017,4,3.0,2.0,789.0,99.0,-37.82140,145.08430,19893,436.569817,23.769231,0,3767,18925,2042
703,ID877736099,13 Rosemary Dr,LALOR,572000.0,h,27/05/2017,3,1.0,2.0,640.0,44.0,-37.65910,145.00549,20006,1275.807884,42.222222,0,1360,6408,691
704,ID337914978,1/36 The Avenue,BALACLAVA,585000.0,u,15/07/2017,2,1.0,1.0,598.0,44.0,-37.87149,144.99746,19956,412.373168,17.500000,0,1672,10063,646
705,ID828387705,13 McDougall St,FAWKNER,619000.0,h,13/08/2016,2,1.0,2.0,640.0,49.0,-37.70380,144.96380,19961,555.657930,39.000000,0,1144,6845,375
706,ID286614327,11 Rebecca Cl,CHELSEA HEIGHTS,835500.0,h,29/07/2017,5,5.0,4.0,570.0,29.0,-38.03335,145.13212,19861,2135.351256,54.153846,0,326,1234,99
707,ID187135066,39 Wilkinson St,BRUNSWICK,800000.0,h,3/09/2017,2,1.0,0.0,140.0,129.0,-37.76806,144.95980,19968,42.110197,25.333333,0,941,5813,575
708,ID582089114,3 Speers Ct,WARRANDYTE,1600000.0,h,19/08/2017,4,2.0,2.0,4168.0,19.0,-37.74611,145.17835,19987,4505.851477,47.900000,0,281,524,75
709,ID634535284,35 Finningley Dr,TULLAMARINE,695000.0,h,27/05/2017,3,1.0,2.0,676.0,39.0,-37.69636,144.88265,20031,2931.266543,38.000000,0,256,511,54
710,ID158999276,124 Cole St,BRIGHTON,1761000.0,h,6/08/2016,4,2.0,3.0,615.0,99.0,-37.89560,145.00260,19953,183.861148,23.500000,0,2744,10289,780
711,ID474719080,14 Arthur St,PRESTON,1065000.0,h,15/10/2016,2,1.0,3.0,507.0,109.0,-37.74370,144.99950,20013,214.591732,26.300000,0,659,5219,338
712,ID550141293,1A Aberfeldie St,ABERFELDIE,1195000.0,h,9/09/2017,3,2.0,2.0,381.0,113.0,-37.75629,144.90626,22253,876.262045,18.333333,0,817,1779,181
713,ID494300549,37 Roberts St,KEILOR EAST,891000.0,h,18/06/2016,3,3.0,1.0,292.0,21.0,-37.75050,144.86570,22253,4491.990846,18.333333,0,555,1129,160
714,ID754507287,416 Serpells Tce,DONVALE,1200000.0,h,19/08/2017,4,2.0,2.0,375.0,21.0,-37.77559,145.17933,19900,4838.187695,34.666667,0,3327,11071,1069
715,ID428230767,1/6 Corhampton Rd,BALWYN NORTH,1600000.0,u,29/07/2017,3,2.0,2.0,314.0,7.0,-37.79386,145.06746,19932,3304.191847,26.000000,0,959,4476,324
716,ID512732811,11/1051 Pascoe Vale Rd,JACANA,280000.0,u,16/04/2016,2,1.0,1.0,197.0,69.0,-37.68590,144.91640,22254,424.787265,32.000000,0,87,252,37
717,ID309630222,7 Eaglet Ct,MILL PARK,720000.0,h,3/06/2017,4,2.0,3.0,649.0,34.0,-37.67681,145.06414,45795,3079.602820,49.222222,0,1508,6073,553
718,ID354076401,8 Norma Ct,AVONDALE HEIGHTS,850000.0,h,3/09/2016,3,1.0,1.0,593.0,49.0,-37.76770,144.86740,20022,3523.830942,21.400000,0,1654,9119,550
719,ID959679005,15 Kingshott Cl,WILLIAMSTOWN,1500000.0,h,29/04/2017,4,3.0,2.0,450.0,13.0,-37.86170,144.87860,19993,1041.011646,20.857143,0,1064,4200,432

In [15]:
#determine the southern cross station is in the stop dataframe or not, is it exist, return the stop id of outhern cross staion
def found_southern(stop):
    for i in range(len(stop)):
        if ('Southern Cross Coach Terminal'in stop.loc[i,'stop_name'])or ('Southern Cross Railway Station'in stop.loc[i,'stop_name']):
            
            return stop.loc[i,'stop_id']
        
    return False

In [16]:
SC_id = []
route_list = []
for i in [1,2,3,4,5,6,7,8,10,11]:
    stop_file = pd.read_csv("gtfs/"+str(i)+"/google_transit/stops.txt")
    if found_southern(stop_file)!= False:
        SC_id.append(found_southern(stop_file))
        route_list.append(i)
SC_id = list(set(SC_id))
print(SC_id)
print(route_list)

[18187, 20043, 22180, 20836]
[1, 2, 3, 4, 5, 10]

In [28]:
# read the calender data to check which service id was only run in the weekday, extract the service_id list
calendar_file = pd.read_csv("gtfs/1/google_transit/calendar.txt")
service_id_list = list(calendar_file[(calendar_file['saturday']==0)&(calendar_file['sunday']==0)]['service_id'].unique())

# read the trips file to check which trip_id is for the service_id list
trips_file = pd.read_csv("gtfs/1/google_transit/trips.txt")
trip_id_list = list(trips_file[trips_file['service_id'].isin(service_id_list)]['trip_id'].unique())

#read stop_time file
time_main = pd.read_csv("gtfs/1/google_transit/stop_times.txt")
#filter the dataframe with the trip_id only work in the weekday first.
time_main = time_main[time_main['trip_id'].isin(trip_id_list)]
#extract the trip have southern cross station included.
SC_trip_id_list = list(time_main[time_main['stop_id'].isin(SC_id)]['trip_id'].unique())
#Filter the time file with the trip id which the trip contain southern cross station
time_main = time_main[(time_main['trip_id'].isin(SC_trip_id_list))]
#extract the stop id which the trip run time between 7:00-9:30.
stop_id_list = time_main[(time_main['arrival_time']> '06:59:59')&(time_main['arrival_time']< '09:30:01')]['stop_id'].unique()
#Adding the route number for better query in the future
time_main['route'] = 1

#Read the stop file
stop_main = pd.read_csv("gtfs/1/google_transit/stops.txt")
#filter stop file with the stop id extract from pervious step
stop_main = stop_main[stop_main['stop_id'].isin(stop_id_list)]
#Adding the route number for better query in the future
stop_main['route'] = 1

print(len(time_main))

42481

97

In [29]:
for i in [2, 3, 4, 5, 10]:
    trip_id_list = []
    stop_id_list = []
    trip_id_list = []
    service_id_list= []
    
    # read the calender data to check which service id was only run in the weekday, extract the service_id list
    calendar_file = pd.read_csv("gtfs/"+str(i)+"/google_transit/calendar.txt")
    service_id_list = list(calendar_file[(calendar_file['saturday']==0)&(calendar_file['sunday']==0)]['service_id'].unique())
    
    # read the trips file to check which trip_id is for the service_id list
    trips_file = pd.read_csv("gtfs/"+str(i)+"/google_transit/trips.txt")
    trip_id_list = list(trips_file[trips_file['service_id'].isin(service_id_list)]['trip_id'].unique())
    
    #read stop_time file
    time_file = pd.read_csv("gtfs/"+str(i)+"/google_transit/stop_times.txt")
    #filter the dataframe with the trip_id only work in the weekday first.
    time_file = time_file[time_file['trip_id'].isin(trip_id_list)]
    #extract the trip have southern cross station included.
    SC_trip_id_list = list(time_file[time_file['stop_id'].isin(SC_id)]['trip_id'].unique())
    #Filter the time file with the trip id which the trip contain southern cross station
    time_file = time_file[time_file['trip_id'].isin(SC_trip_id_list)]
    #extract the stop id which the trip run time between 7:00-9:30.
    stop_id_list = time_file[(time_file['arrival_time']> '06:59:59')&(time_file['arrival_time']< '09:30:01')]['stop_id'].unique()
    #Adding the route number for better query in the future
    time_file['route'] = i
    #Add the file into main file
    time_main = pd.concat([time_main, time_file], ignore_index=True)
    
    #Read the stop file
    stop_file = pd.read_csv("gtfs/"+str(i)+"/google_transit/stops.txt")
    #filter stop file with the stop id extract from pervious step
    stop_file = stop_file[stop_file['stop_id'].isin(stop_id_list)]
    #Adding the route number for better query in the future
    stop_file['route'] = i
    #Add the file into main file
    stop_main = pd.concat([stop_main, stop_file], ignore_index=True)

In [30]:
len(stop_main)

411

In [31]:
len(time_main)

225283

In [32]:
del time_main['stop_headsign']
del time_main['pickup_type']
del time_main['drop_off_type']
del time_main['shape_dist_traveled']
time_main

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,route
0,7548.UR.1-V08-A-mjp-1.1.H,06:08:00,06:08:00,20291,1,1
1,7548.UR.1-V08-A-mjp-1.1.H,06:42:00,06:42:00,20346,2,1
2,7548.UR.1-V08-A-mjp-1.1.H,06:55:00,06:57:00,20341,3,1
3,7548.UR.1-V08-A-mjp-1.1.H,07:16:00,07:16:00,20339,4,1
4,7548.UR.1-V08-A-mjp-1.1.H,07:32:00,07:34:00,20351,5,1
5,7548.UR.1-V08-A-mjp-1.1.H,07:45:00,07:45:00,20330,6,1
6,7548.UR.1-V08-A-mjp-1.1.H,07:57:00,07:57:00,20328,7,1
7,7548.UR.1-V08-A-mjp-1.1.H,08:16:00,08:16:00,20357,10,1
8,7548.UR.1-V08-A-mjp-1.1.H,08:23:00,08:23:00,20308,11,1
9,7548.UR.1-V08-A-mjp-1.1.H,08:36:00,08:36:00,20313,14,1
10,7548.UR.1-V08-A-mjp-1.1.H,08:51:00,08:51:00,22252,17,1
11,7548.UR.1-V08-A-mjp-1.1.H,09:09:00,09:09:00,22250,18,1
12,7548.UR.1-V08-A-mjp-1.1.H,09:36:00,09:36:00,22248,20,1
13,7548.UR.1-V08-A-mjp-1.1.H,09:44:00,09:44:00,22247,21,1
14,7548.UR.1-V08-A-mjp-1.1.H,09:48:00,09:50:00,22238,22,1
15,7548.UR.1-V08-A-mjp-1.1.H,09:57:00,09:57:00,20043,23,1
16,7549.UR.1-V08-A-mjp-1.2.H,12:45:00,12:45:00,20291,1,1
17,7549.UR.1-V08-A-mjp-1.2.H,13:19:00,13:19:00,20346,2,1
18,7549.UR.1-V08-A-mjp-1.2.H,13:33:00,13:35:00,20341,3,1
19,7549.UR.1-V08-A-mjp-1.2.H,13:54:00,13:54:00,20339,4,1
20,7549.UR.1-V08-A-mjp-1.2.H,14:10:00,14:14:00,20351,5,1
21,7549.UR.1-V08-A-mjp-1.2.H,14:23:00,14:23:00,20330,6,1
22,7549.UR.1-V08-A-mjp-1.2.H,14:32:00,14:32:00,20328,7,1
23,7549.UR.1-V08-A-mjp-1.2.H,14:55:00,14:55:00,20357,10,1
24,7549.UR.1-V08-A-mjp-1.2.H,15:01:00,15:01:00,20308,11,1
25,7549.UR.1-V08-A-mjp-1.2.H,15:14:00,15:14:00,20313,14,1
26,7549.UR.1-V08-A-mjp-1.2.H,15:33:00,15:33:00,22252,17,1
27,7549.UR.1-V08-A-mjp-1.2.H,15:49:00,15:49:00,22250,18,1
28,7549.UR.1-V08-A-mjp-1.2.H,16:16:00,16:16:00,22248,20,1
29,7549.UR.1-V08-A-mjp-1.2.H,16:29:00,16:31:00,22238,22,1
...,...,...,...,...,...,...
225253,6993.UW.10-GSR-K-mjp-1.2.R,08:15:00,08:15:00,20600,1,10
225254,6993.UW.10-GSR-K-mjp-1.2.R,10:18:00,10:20:00,20609,3,10
225255,6993.UW.10-GSR-K-mjp-1.2.R,12:17:00,12:19:00,20614,8,10
225256,6993.UW.10-GSR-K-mjp-1.2.R,13:15:00,13:17:00,20616,10,10
225257,6993.UW.10-GSR-K-mjp-1.2.R,13:42:00,13:50:00,20617,11,10
225258,6993.UW.10-GSR-K-mjp-1.2.R,14:15:00,14:17:00,20618,12,10
225259,6993.UW.10-GSR-K-mjp-1.2.R,15:09:00,15:11:00,45918,13,10
225260,6993.UW.10-GSR-K-mjp-1.2.R,15:33:00,15:35:00,20288,14,10
225261,6993.UW.10-GSR-K-mjp-1.2.R,17:37:00,17:39:00,20335,16,10
225262,6993.UW.10-GSR-K-mjp-1.2.R,18:50:00,18:50:00,20043,17,10
225263,7833.T0.10-GSR-L-mjp-1.1.H,08:05:00,08:05:00,20043,1,10
225264,7833.T0.10-GSR-L-mjp-1.1.H,09:13:00,09:15:00,20335,2,10
225265,7833.T0.10-GSR-L-mjp-1.1.H,11:13:00,11:15:00,20288,4,10
225266,7833.T0.10-GSR-L-mjp-1.1.H,11:38:00,11:40:00,45918,5,10
225267,7833.T0.10-GSR-L-mjp-1.1.H,12:29:00,12:31:00,20618,6,10
225268,7833.T0.10-GSR-L-mjp-1.1.H,12:55:00,13:00:00,20617,7,10
225269,7833.T0.10-GSR-L-mjp-1.1.H,13:25:00,13:27:00,20616,8,10
225270,7833.T0.10-GSR-L-mjp-1.1.H,14:19:00,14:21:00,20614,10,10
225271,7833.T0.10-GSR-L-mjp-1.1.H,16:18:00,16:20:00,20609,15,10
225272,7833.T0.10-GSR-L-mjp-1.1.H,18:10:00,18:10:00,20600,17,10
225273,7245.T0.10-GSR-L-mjp-1.2.R,08:15:00,08:15:00,20600,1,10
225274,7245.T0.10-GSR-L-mjp-1.2.R,10:18:00,10:20:00,20609,3,10
225275,7245.T0.10-GSR-L-mjp-1.2.R,12:17:00,12:19:00,20614,8,10
225276,7245.T0.10-GSR-L-mjp-1.2.R,13:15:00,13:17:00,20616,10,10
225277,7245.T0.10-GSR-L-mjp-1.2.R,13:42:00,13:50:00,20617,11,10
225278,7245.T0.10-GSR-L-mjp-1.2.R,14:15:00,14:17:00,20618,12,10
225279,7245.T0.10-GSR-L-mjp-1.2.R,15:09:00,15:11:00,45918,13,10
225280,7245.T0.10-GSR-L-mjp-1.2.R,15:33:00,15:35:00,20288,14,10
225281,7245.T0.10-GSR-L-mjp-1.2.R,17:37:00,17:39:00,20335,16,10
225282,7245.T0.10-GSR-L-mjp-1.2.R,18:50:00,18:50:00,20043,17,10

In [33]:
time_main = time_main[ (time_main['arrival_time']> '06:59:59')&(time_main['arrival_time']< '16:00:00')]

In [34]:
time_main = time_main.reset_index()
del time_main['index']
time_main

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,route
0,7548.UR.1-V08-A-mjp-1.1.H,07:16:00,07:16:00,20339,4,1
1,7548.UR.1-V08-A-mjp-1.1.H,07:32:00,07:34:00,20351,5,1
2,7548.UR.1-V08-A-mjp-1.1.H,07:45:00,07:45:00,20330,6,1
3,7548.UR.1-V08-A-mjp-1.1.H,07:57:00,07:57:00,20328,7,1
4,7548.UR.1-V08-A-mjp-1.1.H,08:16:00,08:16:00,20357,10,1
5,7548.UR.1-V08-A-mjp-1.1.H,08:23:00,08:23:00,20308,11,1
6,7548.UR.1-V08-A-mjp-1.1.H,08:36:00,08:36:00,20313,14,1
7,7548.UR.1-V08-A-mjp-1.1.H,08:51:00,08:51:00,22252,17,1
8,7548.UR.1-V08-A-mjp-1.1.H,09:09:00,09:09:00,22250,18,1
9,7548.UR.1-V08-A-mjp-1.1.H,09:36:00,09:36:00,22248,20,1
10,7548.UR.1-V08-A-mjp-1.1.H,09:44:00,09:44:00,22247,21,1
11,7548.UR.1-V08-A-mjp-1.1.H,09:48:00,09:50:00,22238,22,1
12,7548.UR.1-V08-A-mjp-1.1.H,09:57:00,09:57:00,20043,23,1
13,7549.UR.1-V08-A-mjp-1.2.H,12:45:00,12:45:00,20291,1,1
14,7549.UR.1-V08-A-mjp-1.2.H,13:19:00,13:19:00,20346,2,1
15,7549.UR.1-V08-A-mjp-1.2.H,13:33:00,13:35:00,20341,3,1
16,7549.UR.1-V08-A-mjp-1.2.H,13:54:00,13:54:00,20339,4,1
17,7549.UR.1-V08-A-mjp-1.2.H,14:10:00,14:14:00,20351,5,1
18,7549.UR.1-V08-A-mjp-1.2.H,14:23:00,14:23:00,20330,6,1
19,7549.UR.1-V08-A-mjp-1.2.H,14:32:00,14:32:00,20328,7,1
20,7549.UR.1-V08-A-mjp-1.2.H,14:55:00,14:55:00,20357,10,1
21,7549.UR.1-V08-A-mjp-1.2.H,15:01:00,15:01:00,20308,11,1
22,7549.UR.1-V08-A-mjp-1.2.H,15:14:00,15:14:00,20313,14,1
23,7549.UR.1-V08-A-mjp-1.2.H,15:33:00,15:33:00,22252,17,1
24,7549.UR.1-V08-A-mjp-1.2.H,15:49:00,15:49:00,22250,18,1
25,7779.UR.1-V08-A-mjp-1.3.R,07:20:00,07:20:00,20043,1,1
26,7779.UR.1-V08-A-mjp-1.3.R,07:24:00,07:26:00,22238,2,1
27,7779.UR.1-V08-A-mjp-1.3.R,07:38:00,07:38:00,22248,4,1
28,7779.UR.1-V08-A-mjp-1.3.R,08:05:00,08:05:00,22250,6,1
29,7779.UR.1-V08-A-mjp-1.3.R,08:26:00,08:26:00,22252,7,1
...,...,...,...,...,...,...
119139,5570.T0.10-GSR-K-mjp-1.2.R,12:17:00,12:19:00,20614,8,10
119140,5570.T0.10-GSR-K-mjp-1.2.R,13:15:00,13:17:00,20616,10,10
119141,5570.T0.10-GSR-K-mjp-1.2.R,13:42:00,13:50:00,20617,11,10
119142,5570.T0.10-GSR-K-mjp-1.2.R,14:15:00,14:17:00,20618,12,10
119143,5570.T0.10-GSR-K-mjp-1.2.R,15:09:00,15:11:00,45918,13,10
119144,5570.T0.10-GSR-K-mjp-1.2.R,15:33:00,15:35:00,20288,14,10
119145,6993.UW.10-GSR-K-mjp-1.2.R,08:15:00,08:15:00,20600,1,10
119146,6993.UW.10-GSR-K-mjp-1.2.R,10:18:00,10:20:00,20609,3,10
119147,6993.UW.10-GSR-K-mjp-1.2.R,12:17:00,12:19:00,20614,8,10
119148,6993.UW.10-GSR-K-mjp-1.2.R,13:15:00,13:17:00,20616,10,10
119149,6993.UW.10-GSR-K-mjp-1.2.R,13:42:00,13:50:00,20617,11,10
119150,6993.UW.10-GSR-K-mjp-1.2.R,14:15:00,14:17:00,20618,12,10
119151,6993.UW.10-GSR-K-mjp-1.2.R,15:09:00,15:11:00,45918,13,10
119152,6993.UW.10-GSR-K-mjp-1.2.R,15:33:00,15:35:00,20288,14,10
119153,7833.T0.10-GSR-L-mjp-1.1.H,08:05:00,08:05:00,20043,1,10
119154,7833.T0.10-GSR-L-mjp-1.1.H,09:13:00,09:15:00,20335,2,10
119155,7833.T0.10-GSR-L-mjp-1.1.H,11:13:00,11:15:00,20288,4,10
119156,7833.T0.10-GSR-L-mjp-1.1.H,11:38:00,11:40:00,45918,5,10
119157,7833.T0.10-GSR-L-mjp-1.1.H,12:29:00,12:31:00,20618,6,10
119158,7833.T0.10-GSR-L-mjp-1.1.H,12:55:00,13:00:00,20617,7,10
119159,7833.T0.10-GSR-L-mjp-1.1.H,13:25:00,13:27:00,20616,8,10
119160,7833.T0.10-GSR-L-mjp-1.1.H,14:19:00,14:21:00,20614,10,10
119161,7245.T0.10-GSR-L-mjp-1.2.R,08:15:00,08:15:00,20600,1,10
119162,7245.T0.10-GSR-L-mjp-1.2.R,10:18:00,10:20:00,20609,3,10
119163,7245.T0.10-GSR-L-mjp-1.2.R,12:17:00,12:19:00,20614,8,10
119164,7245.T0.10-GSR-L-mjp-1.2.R,13:15:00,13:17:00,20616,10,10
119165,7245.T0.10-GSR-L-mjp-1.2.R,13:42:00,13:50:00,20617,11,10
119166,7245.T0.10-GSR-L-mjp-1.2.R,14:15:00,14:17:00,20618,12,10
119167,7245.T0.10-GSR-L-mjp-1.2.R,15:09:00,15:11:00,45918,13,10
119168,7245.T0.10-GSR-L-mjp-1.2.R,15:33:00,15:35:00,20288,14,10

In [35]:
time_main.to_csv('time_main.csv',index=False)
stop_main.to_csv('stop_main.csv',index=False)

In [37]:
stop_main

,stop_id,stop_name,stop_lat,stop_lon,route
0,17204,Wallan Railway Station (Wallan),-37.416861,145.005372,1
1,19980,Melton Railway Station (Melton South),-37.703293,144.572524,1
2,19981,Rockbank Railway Station (Rockbank),-37.729261,144.650631,1
3,19982,Deer Park Railway Station (Deer Park),-37.777764,144.772304,1
4,19998,Sunbury Railway Station (Sunbury),-37.579206,144.728165,1
5,20020,Ardeer Railway Station (Ardeer),-37.783065,144.802188,1
6,20029,Craigieburn Railway Station (Craigieburn),-37.601925,144.943306,1
7,20043,Southern Cross Railway Station (Melbourne City),-37.818334,144.952525,1
8,20288,Ararat Railway Station (Ararat),-37.282205,142.936914,1
9,20289,Avenel Railway Station (Avenel),-36.893648,145.229515,1
10,20290,Bacchus Marsh Railway Station (Maddingley),-37.687578,144.436785,1
11,20292,Ballan Railway Station (Ballan),-37.604300,144.225448,1
12,20293,Ballarat Railway Station (Ballarat Central),-37.558791,143.859457,1
13,20294,Beaufort Railway Station (Beaufort),-37.427875,143.382234,1
14,20295,Benalla Railway Station (Benalla),-36.544550,145.983915,1
15,20296,Bendigo Railway Station (Bendigo),-36.765670,144.283009,1
16,20297,Birregurra Railway Station (Birregurra),-38.328808,143.783625,1
17,20298,Broadford Railway Station (Broadford),-37.207200,145.043008,1
18,20299,Bunyip Railway Station (Bunyip),-38.099108,145.720757,1
19,20300,Camperdown Railway Station (Camperdown),-38.228901,143.150928,1
20,20301,Castlemaine Railway Station (Castlemaine),-37.062837,144.213799,1
21,20302,Chiltern Railway Station (Chiltern),-36.155637,146.611375,1
22,20303,Clarkefield Railway Station (Clarkefield),-37.483498,144.745373,1
23,20304,Colac Railway Station (Colac),-38.343378,143.586653,1
24,20305,Corio Railway Station (Corio),-38.072831,144.379768,1
25,20306,Dingee Railway Station (Dingee),-36.369233,144.231120,1
26,20307,Donnybrook Railway Station (Donnybrook),-37.542590,144.969860,1
27,20308,Drouin Railway Station (Drouin),-38.136452,145.855947,1
28,20309,Eaglehawk Railway Station (Eaglehawk),-36.718525,144.248380,1
29,20310,Echuca Railway Station (Echuca),-36.130982,144.753459,1
...,...,...,...,...,...
381,17353,Welsford St/South Gippsland Hwy (Meeniyan),-38.578944,146.011981,5
382,17355,Neals Rd/Meeniyan - Promontory Rd (Buffalo),-38.649855,146.018121,5
383,17357,Roo Fuel/Meeniyan - Promontory Rd (Fish Creek),-38.694147,146.082564,5
384,17358,Pulhams Store/Main St (Foster),-38.652214,146.200169,5
385,17581,Hogan St/Fraser St (Tatura),-36.440476,145.225309,5
386,17586,Silver Creek Rd/Whittlesea-Yea Rd (Hazeldene),-37.374438,145.280070,5
387,17588,Hazeldene Bridge/Whittlesea-Yea Rd (Hazeldene),-37.344195,145.289024,5
388,17589,Flowerdale Hotel/Whittlesea-Yea Rd (Flowerdale),-37.320697,145.288327,5
389,18671,east of Pechell St/High St (Yea),-37.211162,145.423981,5
390,18672,General Store/Goulburn Valley Hwy (Molesworth),-37.167309,145.539051,5
391,18674,Wrights St/Maroondah Hwy (Yarck),-37.101185,145.617078,5
392,18676,Euroa - Mansfield Rd/Maroondah Hwy (Merton),-36.977321,145.710830,5
393,18678,Woolshed Rd/Maroondah Hwy (Woodfield),-37.022249,145.806827,5
394,18682,Opposite CFA/Maroondah Hwy (Maindample),-37.028818,145.940500,5
395,18683,MMBL Depot/High St (Mansfield),-37.051627,146.086158,5
396,20836,Southern Cross Coach Terminal/Spencer St (Melb...,-37.815084,144.951149,5
397,20877,Echuca Railway Station (Echuca),-36.131111,144.753611,5
398,20889,Caltex Service Station/Waverley Ave (Merrigum),-36.371854,145.132026,5
399,20900,Walker Park/Whitehorse Rd (Nunawading),-37.817326,145.185038,5
400,21263,Caltex Roadhouse Rose St/Northern Hwy (Echuca),-36.144750,144.730240,5
401,36894,Colbinabbin General Store/Mitchell St (Colbina...,-36.590378,144.796172,5
402,46509,General Store/Whittlesea-Yea Rd (Kinglake West),-37.475771,145.236904,5
403,46510,Phillip St/Bon Cres (Bonnie Doon),-37.026569,145.853685,5
404,47101,Koala Dr/Swan Rd (Koonwarra),-38.546691,145.946842,5
405,5102,Watts St/Whitehorse Rd (Box Hill),-37.818082,145.125695,5
406,7739,Walnut St/Church St (Whittlesea),-37.512457,145.118082,5
407,7877,Eastland SC/Warrandyte Rd (Ringwood),-37.812460,145.230652,5
408,20043,Southern Cross Railway Station (Melbourne City),-37.818334,144.952525,10
409,20335,North Shore Railway Station (North Shore),-38.098377,144.365321,10
410,20600,Adelaide Railway Station (Adelaide City (SA)),-34.938055,138.579719,10

In [16]:
from geopy.distance import geodesic
print(geodesic((30.28708,120.12802999999997), (28.7427,115.86572000000001)).m)

447249.7993542003

In [40]:
test = [1,2,3,4]
def calculate_mean(calculate_list):
    result = 0
    for i in calculate_list:
        result+=i
    return result/len(calculate_list)
calculate_mean(test)

2.5

In [ ]:
!conda install geopandas

In [13]:
!pip install --upgrade setupTools

Requirement already up-to-date: setupTools in c:\users\david\appdata\roaming\python\python37\site-packages (41.0.1)